/**
 * Created by yyj on 16/12/2016.
 */

export const AUTH = {
  START: 'AUTH_START',
  COMPLETE: 'AUTH_COMPLETE',
  ERROR: 'AUTH_ERROR',
  LOGOUT: 'START_LOGOUT',
  CHECK_AUTH: 'CHECK_AUTH',
  //
  SET_USER: 'SET_USER',

};

export const UI = {
  SHOW_SPINNER: 'SHOW_SPINNER',
  HIDE_SPINNER: 'HIDE_SPINNER',
  SET_UI: 'SET_UI',
};

export const RECIPES = {
  GET_RECIPES: 'GET_RECIPES',
  SET_RECIPE: 'SET_RECIPE',
  ADD_RECIPE: 'ADD_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
};
